# Generated by Django 5.1.5 on 2025-04-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='isbn13',
        ),
        migrations.AddField(
            model_name='book',
            name='img_src',
            field=models.CharField(default='No Image'),
        ),
    ]
